name: CI/CD with Trivy + SonarCloud + Argo CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sathish404/demo-nginx-argocd

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: SonarCloud Static Code Analysis (before build)
    - name: Set up Java (required for SonarCloud CLI)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Step 3: Set up Docker and Tag
    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Get short SHA tag
      id: vars
      run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 4: Build and Push Docker Image
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

    # Step 5: Trivy Image Vulnerability Scan
    - name: Run Trivy scan (JSON)
      run: |
        docker run --rm -v ${{ github.workspace }}:/root aquasec/trivy:latest \
          image --format json --output /root/trivy-report.json \
          ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

    - name: Upload Trivy report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: trivy-report.json

    - name: Fail if critical vulnerabilities found
      run: |
        count=$(jq '[.Results[] | select(.Vulnerabilities != null) | .Vulnerabilities[] | select(.Severity=="CRITICAL")] | length' trivy-report.json)
        echo "Found $count critical vulnerabilities"
        if [ "$count" -gt 0 ]; then
          echo "❌ Build failed due to critical vulnerabilities"
          exit 1
        fi

    # Optional: Upload to GitHub Security Dashboard (SARIF)
    - name: Run Trivy scan (SARIF)
      run: |
        docker run --rm -v ${{ github.workspace }}:/root aquasec/trivy:latest \
          image --format sarif --output /root/trivy-results.sarif \
          ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

    - name: Upload SARIF to GitHub Security Dashboard
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: trivy-results.sarif

    # Step 6: Update Deployment YAML
    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|image: .*|image: ${IMAGE_NAME}:${{ steps.vars.outputs.TAG }}|" k8s/deployment.yaml

    # Step 7: Commit and Push Manifest
    - name: Commit and push updated manifest
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ steps.vars.outputs.TAG }}"
        git push
