name: CI/CD with Argo CD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: sathish404/demo-nginx-argocd

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get short SHA tag
      id: vars
      run: echo "TAG=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.TAG }}

    - name: Update image tag in deployment.yaml
      run: |
        sed -i "s|image: .*$|image: ${IMAGE_NAME}:${{ steps.vars.outputs.TAG }}|" k8s/deployment.yaml

    - name: Commit and push updated manifest
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add k8s/deployment.yaml
        git commit -m "Update image tag to ${{ steps.vars.outputs.TAG }}"
        git push
